# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAppleRobertoG' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestAppleRobertoG

	pod 'TextFieldEffects'
	pod 'Firebase/Core'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Database'
  	pod 'Firebase/Messaging’
  	pod 'Firebase/Storage'
	pod 'Firebase/Firestore'
  	pod 'SDWebImage'
	pod 'FacebookCore'
  	pod 'FacebookLogin'
  	pod 'FacebookShare'
	pod 'GoogleMaps'
  	pod 'GooglePlaces'
	pod 'GoogleSignIn'
	pod 'TwitterKit'
	pod 'GooglePlacesSearchController'
	pod 'GooglePlacePicker'
	pod 'HockeySDK'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Alamofire’
 	pod 'SwiftyJSON', :git => 'https://github.com/acegreen/SwiftyJSON.git', :branch => 'swift3'
	pod 'Firebase/Analytics'

  
end
